CREATE TABLE [dbo].[Testing]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[ProductCode] NVARCHAR(50) NOT NULL	,
	[ProductName] NVARCHAR(100) NOT NULL,
	[Manufacturer] NVARCHAR(100) NOT NULL,
	[ShippingNo] NVARCHAR(100) NOT NULL,
	[SerialNo] INT NULL,
	[BatchNo] NVARCHAR(100) NOT NULL,
	[MRP] DECIMAL(18,2) NOT NULL,
	[Quantity] INT NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[LastModifiedOn] DATETIME2 NULL,
)